### ISSUE TITLE
Perl testing: automate file listing

### ISSUE THREAD

**Issue by GreyCat** [kaitai-io/kaitai_struct_tests#12]
I keep noticing that current Perl test runner (`spec/perl/_run.pl`) uses fixed list of test files to run:

```perl
my @tests = (
    'spec/perl/TestBufferedStruct.t',
    'spec/perl/TestDefaultBigEndian.t',
    'spec/perl/TestEnum0.t',
    'spec/perl/TestEnumIf.t',
...
```

This is generally not a good idea, and it brings more pain that its potential benefits. Tests are created frequently by automated porting scripts, so adding them all 

Some languages indeed have lists of files in their build / run scripts (C#, C++), but that's mostly because that's a requirement of their build systems. I really hope that one day we'll automate their builds as well.

Note that it's not necessary to list all tests for sake of "completeness", because we have higher-level test result aggregation framework that automatically takes care of that - as long as any language has cerain test run, every other language's missing test with the same name would be considered as "didn't run", and would be clearly visible in [CI results](http://kaitai.io/ci/).

Could you replace this hard-coded list of test files with some auto-discovery? I believe that Perl has [glob](http://perldoc.perl.org/functions/glob.html) that can be used to get that file list.

**Comment by sergeyzelenyuk** [comment]
It's a good idea, thanks! I've done it.

**Comment by GreyCat** [comment]
But why did you commented out all the converted test files? If they fail for now, that ok - that's exactly the sign that we need to fix them.

**Comment by sergeyzelenyuk** [comment]
I think it's more readable by human to see something like that:
```
spec/perl/TestFixedStruct.t ......... No subtests run
```
than long syntax error messages:
```
spec/perl/TestFixedStruct.t ......... Scalar found where operator expected at ../runtime/perl/FixedStruct.pm line 74, near ")
    $self"
	(Missing operator before $self?)
Scalar found where operator expected at ../runtime/perl/FixedStruct.pm line 77, near ")
    $self"
	(Missing operator before $self?)
Scalar found where operator expected at ../runtime/perl/FixedStruct.pm line 81, near ")
    $self"
...
```
when writing the tests.

**Comment by GreyCat** [comment]
Well, it kind of slows down the development, as you'll have to uncomment the tests you want to check every time you want it to actually run. The whole CI / "testing first" practice is actually about tests come first and remain "broken" until the code is complete. As soon as it's all green - we're good to go.
