### ISSUE TITLE
run-javascript fails on Windows

### ISSUE THREAD

**Issue by tschoening** [kaitai-io/kaitai_struct_tests#18]
Your are using NODE_PATH in `run_javascript` with `:`, which doesn't work on Windows even in some Posix like environment like Git Bash. One needs to use `;` and afterwards this only works if the variable assignment is used in `"`, because else the shell tries to concatenate and execute commands.

Don't know how/if you want to deal with that, this is my workaround currently:

	# (Note: On Windows, NODE_PATH is delimited by semicolons instead of colons.)
	# https://nodejs.org/api/modules.html#modules_loading_from_the_global_folders
	DIVIDER=":"
	if [ ${OS} = "Windows_NT" ]
	then
		DIVIDER=";"
	fi

	NODE_PATH="compiled/javascript${DIVIDER}helpers/javascript${DIVIDER}$JAVASCRIPT_MODULES_DIR${DIVIDER}$JAVASCRIPT_RUNTIME_DIR" \
		$JAVASCRIPT_MODULES_DIR/mocha/bin/mocha spec/javascript

**Comment by GreyCat** [comment]
I guess no one tried to run these scripts on Windows yet, so it's natural that some bugs arise :(
Thanks for this correction, such solution will work just fine. The only thing I would have changed is formatting and $OS quoting, i.e.

```shell
if [ "$OS" = "Windows_NT" ]; then
    DIVIDER=";"
else
    DIVIDER=":"
fi
```

**Comment by tschoening** [comment]
This is merged now.
