### ISSUE TITLE
Uncaught ReferenceError: OpaqueExternalType02Child is not defined

### ISSUE THREAD

**Issue by tschoening** [kaitai-io/kaitai_struct_tests#19]
After using `spec_translate_missing`, a JavaScript spec is successfully generated, but it's not executable. The child type of my test needed to trigger the actual problem isn't `required` and even if it's `required` manually on the top level, that doesn't change anything.

>  1) OpaqueExternalType02Parent parses test properly:
     Uncaught ReferenceError: OpaqueExternalType02Child is not defined
      at new Parent (compiled\javascript\OpaqueExternalType02Parent.js:18:24)
      at new OpaqueExternalType02Parent (compiled\javascript\OpaqueExternalType02Parent.js:9:19)
      at helpers\javascript\testHelper.js:12:17
      at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)

Doesn't work:

	var assert = require('assert');
	var testHelper = require('testHelper');
	var OpaqueExternalType02Child = require('OpaqueExternalType02Child');

	testHelper('OpaqueExternalType02Parent', 'src/term_strz.bin', function(r) {
	  assert.equal(r.parent.child.s1, 'foo');
	  assert.equal(r.parent.child.s2, 'bar');
	  assert.equal(r.parent.child.s3.s3, '|baz@');
	});

**Comment by GreyCat** [comment]
Actually, it was a bug in TypeProcessor: https://github.com/kaitai-io/kaitai_struct_compiler/commit/d1f1db201706b48325614c9876caeb24c5b08cf6 — it affected Python and C++ as well. Thanks to your test, we've revealed and fixed it ;)
